repos:
-   repo: https://github.com/dubzn/pre-commit-cairo
    rev: v2.3.0
    hooks:
    -   id: fmt
    -   id: test
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black